[wip] Feature/empty state
Sysvale/component-library pull request #31
Opened 2020-03-18 14:54 UTC by Carol111

#### What is the purpose of this pull request?
Creates the EmptyState component

#### How should this be manually tested?

#### Screenshots or example usage
![image](https://user-images.githubusercontent.com/26309807/76973569-e1faf380-690e-11ea-8844-7eddc157e1f2.png)

#### Types of changes
- [x]  New feature (a change which adds functionality)
- [ ] Hot fix (a change which fixes an issue found in the master branch)
- [ ]  Documentation change

2020-03-18 17:52 UTC, RafaelGondi commented on .storybook/config.js
> +	EmptyState
It would be great if you could put a common in the end of the line

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +		<img :src="emptyStateImage" :alt="imgDescription">
```suggestion
		<img
			:src="emptyStateImage"
			:alt="imgDescription"
		/>
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +		<div class="no-items-text"
```suggestion
		<div
			class="no-items-text"
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +			:style="headlineStyle">
```suggestion
			:style="headlineStyle"
		>
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +		<div class="no-items-bodytext mt-2"
```suggestion
		<div
			class="no-items-bodytext mt-2"
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +			:style="bodyTextStyle">
```suggestion
			:style="bodyTextStyle"
		>
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +
```suggestion
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +			description: `The Hex color code for the headline.`
```suggestion
			description: 'The Hex color code for the headline.'
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +			description: `The Hex color code for the body text.`
```suggestion
			description: 'The Hex color code for the body text.'
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +			description: `The Hex color code for the button.`
```suggestion
			description: 'The Hex color code for the button.'
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +			description: `The value, in pixels, of the
```suggestion
			description: 'The value, in pixels, of the font size of the headline. The maximum value accepted is 60px.'
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +				font size of the headline.`,
```suggestion
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +				font size of the body text.`,
```suggestion
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +			description: `The value, in pixels, of the
```suggestion
			description: 'The value, in pixels, of the font size of the body text. The maximum value accepted is 30px.'
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +				font size of the button.`,
```suggestion
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +			description: `The value, in pixels, of the
```suggestion
			description: 'The value, in pixels, of the font size of the button font size. The maximum value accepted is 30px.'
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +				radius of the button.`,
```suggestion
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +			description: `The value, in pixels, of the border
```suggestion
			description: 'The value, in pixels, button border radius. The maximum value accepted is 30px.'
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +
```suggestion
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +
```suggestion
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +    box-shadow: none !important;
Please fix the identation

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +</style>
Please replace the identations with spaces by tab identations

2020-03-18 17:52 UTC, RafaelGondi commented on src/stories/EmptyState.stories.js
> +
```suggestion
```

2020-03-18 17:52 UTC, RafaelGondi commented on src/stories/EmptyState.stories.js
> +
```suggestion
```

2020-03-18 17:52 UTC, RafaelGondi commented on test/unit/EmptyState.spec.js
> +});
```suggestion
});

```

2020-03-18 17:52 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +				@click="$emit('add-button-click')"
```suggestion
				@click="$emit('add-button-click', true)"
```

2020-03-18 17:52 UTC, RafaelGondi commented on test/unit/EmptyState.spec.js
> +test('Component is mounted properly', () => {
Use this test to make a snapshot test in order to see if the component in mounted properly, and create another test to put the expectation "expect(wrapper.findAll('.add-button-container').length).toBe(1);"

2020-03-18 17:52 UTC, RafaelGondi commented on test/unit/EmptyState.spec.js
> +import { mount, createLocalVue } from '@vue/test-utils';
It would be great if you could create a test to check if the event `add-button-click` is emited properly when the button is clicked

2020-03-18 17:56 UTC, esron commented
There are some minors issues in this component:

- You can choose the color and the size of the component texts, but you cannot choose the font. This could be an style object?
- I think that button shouldn't be a part of the component or at least be called Action Button;
- You can't change the button text color or anything.

2020-03-18 18:02 UTC, RafaelGondi commented on src/components/EmptyState.vue
> +		<img :src="emptyStateImage" :alt="imgDescription">
It would be great if we could set a maximum width and heigth of the image in order to prevent layout breaks

2020-03-18 18:02 UTC, esron requested changes

2020-03-18 18:02 UTC, esron commented on src/components/EmptyState.vue
> +    box-shadow: none !important;
Here you indented with spaces.

2020-03-18 18:04 UTC, esron commented
> * You can't change the button t

This can be solved by using the texts as slots. It can be done? If not we can postpone this for the future.

2020-03-18 18:50 UTC, RafaelGondi commented
> > * You can't change the button t
> 
> This can be solved by using the texts as slots. It can be done? If not we can postpone this for the future.

This fix is progress and  it's quite simple, but replace the button by a slot would be a great solution indeed. I think that we can make this improvement in a next version of the component

2020-03-18 18:52 UTC, RafaelGondi commented
> There are some minors issues in this component:
> 
> * You can choose the color and the size of the component texts, but you cannot choose the font. This could be an style object?
> * I think that button shouldn't be a part of the component or at least be called Action Button;
> * You can't change the button text color or anything.

The font is managed by the projects that uses the library

2020-03-19 18:13 UTC, esron approved these changes

2020-03-19 18:14 UTC, merged