feature/improve-docs-creation
Sysvale/component-library pull request #39
Opened 2020-06-29 17:43 UTC by RafaelGondi

#### What is the purpose of this pull request?
Improves the docs creation

#### How should this be manually tested?
* Test if every component is been shown correctly and their interactions are no broken;
*  Test if the side navigation is working properly

#### Screenshots or example usage
![image](https://user-images.githubusercontent.com/20057968/86034850-b7dac680-ba11-11ea-991d-63662704dd37.png)

#### Types of changes
- [x]  New feature (a change which adds functionality)
- [ ] Hot fix (a change which fixes an issue found in the master branch)
- [ ]  Documentation change

2020-06-29 18:46 UTC, tassiocaique requested changes

2020-06-29 18:46 UTC, tassiocaique commented on src/stories/ActionBar.stories.js
> +        whenToUSe: [
The `s` in `whenToUSe` should be in lowercase, I guess.

2020-06-29 19:40 UTC, lucasn4s approved these changes

2020-06-30 12:06 UTC, tassiocaique approved these changes

2020-06-30 12:07 UTC, merged